Minor Updates After React Migration
Wolfinbarger/game-recommender pull request #55
Opened 2024-01-15 01:40 UTC by FreakyNobleGas

I initially went in to update the ReadMe since it still reference Next.js after the reference, but decided to cleanup the SCSS files and some other things along the way.

I also updated the URL for the API call since that was causing a CORS issue in Chrome specifically.

Screenshot of UI after changes
<img width="1468" alt="image" src="https://github.com/Wolfinbarger/game-recommender/assets/31631401/567eb1d8-0933-4583-a209-a67ccec46fd1">

2024-01-16 03:46 UTC, Wolfinbarger reviewed
Maybe, leave the footer in. Was thinking of using it as the loading message for the scroll. Instead of it just straight saying "loading".

2024-01-16 12:00 UTC, FreakyNobleGas commented
That's a good idea

2024-01-17 01:46 UTC, Wolfinbarger requested changes
Restore Footer

2024-01-17 19:41 UTC, Wolfinbarger approved these changes

2024-01-17 19:41 UTC, merged