create next.js front-end
Wolfinbarger/game-recommender pull request #9
Opened 2023-08-28 11:46 UTC by Wolfinbarger

Initialize Next.js app in the app folder.

Response to issue #3

2023-08-28 12:46 UTC, FreakyNobleGas requested changes
This looks great! I tested on my machine and it works for me. Just ask that we remove a couple lines from the ReadMe since it'll be confusing later on.

2023-08-28 12:46 UTC, FreakyNobleGas commented on src/app/README.md
> +
I think we can remove these lines since it's already been completed.

2023-08-29 00:15 UTC, FreakyNobleGas approved these changes
🚀

2023-08-29 01:24 UTC, Wolfinbarger commented
I'mma mergin

2023-08-29 01:24 UTC, merged